version: '3'
services:
  db:
    image: postgres:16.0
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bokkit
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data:z
