server:
  port: 5001
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bokkit}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    validation-query: select 1
    hikari:
      schema: ${DB_SCHEMA:bokkit}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${DB_JPA_HIBERNATE_DDL_AUTO:none}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: bokkit
  profiles:
    include: db

management:
  server:
    port: 5002
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always

